# This is an example configuration file.
Allow = [
  "clique_getSigners",
  "clique_getSignersAtHash",
  "clique_getSnapshot",
  "clique_getSnapshotAtHash",
  "clique_getVoters",
  "clique_getVotersAtHash",
  "eth_blockNumber",
  "eth_call",
  "eth_chainId",
  "eth_estimateGas",
  "eth_gasPrice",
  "eth_genesisAlloc",
  "eth_getBalance",
  "eth_getBlockByHash",
  "eth_getBlockByNumber",
  "eth_getBlockTransactionCountByHash",
  "eth_getBlockTransactionCountByNumber",
  "eth_getCode",
  "eth_getFilterChanges",
  "eth_getLogs",
  "eth_getStorageAt",
  "eth_getTransactionByBlockHashAndIndex",
  "eth_getTransactionByBlockNumberAndIndex",
  "eth_getTransactionByHash",
  "eth_getTransactionCount",
  "eth_getTransactionReceipt",
  "eth_newBlockFilter",
  "eth_newPendingTransactionFilter",
  "eth_sendRawTransaction",
  "eth_subscribe",
  "eth_totalSupply",
  "eth_uninstallFilter",
  "eth_unsubscribe",
  "net_listening",
  "net_version",
  "rpc_modules",
  "web3_clientVersion",
]

SCAddress=[
"0x60a6e5af0525523a617cf6c1f85353fba0408a7b",
"0x68d866baafa993bc002cd35218c13f10ac54221d",
"0xdd15a18b453eb92140a149f774d1c792919bb352",
]